### ISSUE TITLE
D2DOverlay.lib x86

### ISSUE THREAD

**Issue by gandlf** [coltonon/D2DOverlay#2]
Can you please share the D2DOverlay.lib for x86 or the src of the lib? Need it for internal 32 bit game.

**Comment by fqdeng** [comment]
You can compile it by setting x86 release or put main folder Source.cpp in your sources folder and remove #progrma related code.

**Comment by coltonon** [comment]
Yeah, you should be fine compiling it in x86.  Also you can just include the entire src file, you don't need to compile it to a lib.
